// THIS FILE IS AUTOMATICALLY GENERATED. DO NOT MODIFY IT.

import { AssetField, Entry, ContentfulCollection } from "contentful";
import { Document } from "@contentful/rich-text-types";

export interface IContentFields {
  /** Name */
  name: string;

  /** Content */
  content: Document;
}

/** Generic Content Component */

export interface IContent extends IContentFields {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "content";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface IDocumentFields {
  /** Title */
  title: string;

  /** Document */
  document: AssetField;
}

export interface IDocument extends IDocumentFields {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "document";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface IDocumentPageFields {
  /** Page Title */
  pageTitle: string;

  /** Documents */
  documentsCollection: ContentfulCollection<IDocument>;
}

export interface IDocumentPage extends Entry<IDocumentPageFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "documentPage";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface IListPageFields {
  /** Page Title */
  pageTitle: string;

  /** Links */
  links: (ILorePage | IListPage | IMapPage)[];
}

/** A List of Links to Other content */

export interface IListPage extends Entry<IListPageFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "listPage";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface ILorePageFields {
  /** Content Name */
  contentName: string;

  /** Page Title */
  pageTitle: string;

  /** Page Content */
  pageContent: Entry<{ [fieldId: string]: unknown }>[];
}

/** A page for lore a load of rich text boxes and images most likely. Will replace the "Content" type in the old world. */

export interface ILorePage extends Entry<ILorePageFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "lorePage";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface IMapPageFields {
  /** Page Title */
  pageTitle: string;

  unitOfDistance: string | null;

  levelOfDetail: number | null;

  /** Map */
  map: Asset;
}

export interface IMapPage extends Entry<IMapPageFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "mapPage";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface ISessionFields {
  /** Session Number */
  sessionNumber: number;

  /** Location */
  location: string;

  /** Short Description */
  shortDescription: string;

  /** Long Description: */
  longDescription: Document;
}

export interface ISession extends Entry<ISessionFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "session";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface ISessionLocationFields {
  /** displayText */
  displayText: string;
}

/** Location for Session */

export interface ISessionLocation extends Entry<ISessionLocationFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "sessionLocation";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface ISessionsPageFields {
  /** data */
  data: (ISession | ISessionLocation | ISessionStoryIncrement)[];

  /** name */
  name: string;
}

/** Sessions Page */

export interface ISessionsPage extends Entry<ISessionsPageFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "sessionsPage";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface ISessionStoryIncrementFields {
  /** increment */
  increment: "act" | "chapter";

  /** displayText */
  displayText: string;
}

/** For the Sessions increments the story */

export interface ISessionStoryIncrement
  extends Entry<ISessionStoryIncrementFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "sessionStoryIncrement";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface ITemplate5050Fields {
  /** Name */
  name: string;

  /** Left Content */
  leftContent: Entry<{ [fieldId: string]: unknown }>[];

  /** Right Content */
  rightContent: Entry<{ [fieldId: string]: unknown }>[];
}

/** A template that has content on the left and the right */

export interface ITemplate5050 extends Entry<ITemplate5050Fields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "template5050";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export type CONTENT_TYPE =
  | "content"
  | "document"
  | "documentPage"
  | "listPage"
  | "lorePage"
  | "mapPage"
  | "session"
  | "sessionLocation"
  | "sessionsPage"
  | "sessionStoryIncrement"
  | "template5050";

export type IEntry =
  | IContent
  | IDocument
  | IDocumentPage
  | IListPage
  | ILorePage
  | IMapPage
  | ISession
  | ISessionLocation
  | ISessionsPage
  | ISessionStoryIncrement
  | ITemplate5050;

export type LOCALE_CODE = "en-US";

export type CONTENTFUL_DEFAULT_LOCALE_CODE = "en-US";
