# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: "us-east-1"
      REACT_APP_CONTENTFUL_ACCESS_TOKEN: ${{ secrets.REACT_APP_CONTENTFUL_ACCESS_TOKEN }}
      REACT_APP_CONTENTFUL_CMA_ACCESS_TOKEN: ${{ secrets.REACT_APP_CONTENTFUL_CMA_ACCESS_TOKEN }}
      REACT_APP_CONTENTFUL_ENVIRONMENT: ${{ secrets.REACT_APP_CONTENTFUL_ENVIRONMENT }}
      REACT_APP_CONTENTFUL_PREVIEW_ACCESS_TOKEN: ${{ secrets.REACT_APP_CONTENTFUL_PREVIEW_ACCESS_TOKEN }}
      REACT_APP_CONTENTFUL_SPACE_ID: ${{ secrets.REACT_APP_CONTENTFUL_SPACE_ID }}
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: "npm"
      - run: yarn install
      - run: yarn build
      - run: yarn sync
      - run: yarn invalidate
